---
title: "Bootstrapping"
output: github_document
---

```{r}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

```{r}
n_samp = 250

sim_df_const = 
  tibble(
    x = rnorm(n_samp, 1, 1),
    error = rnorm(n_samp, 0, 1),
    y = 2 + 3 * x + error
  )

sim_df_nonconst = sim_df_const %>% 
  mutate(
  error = error * .75 * x,
  y = 2 + 3 * x + error
)

sim_df_nonconst %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5) 

```

```{r}
sim_df_nonconst %>% 
  lm(y ~x, data = .) %>% 
  broom:: tidy()
```


```{r}
sim_df = 
  bind_rows(const = sim_df_const, nonconst = sim_df_nonconst, .id = "data_source") 

sim_df %>% 
  ggplot(aes(x = x, y = y)) + 
  geom_point(alpha = .5) +
  stat_smooth(method = "lm") +
  facet_grid(~data_source) 
```


## Drawing one bootstrap sample
```{r}
bootstrap = 
sim_df_nonconst %>% 
  sample_frac(size =1, replace = TRUE) %>% 
  arrange(x)

lm(y~x, data = bootstrap)
```

Let's write function
```{r}
boot_sample = function(df) {
  sample_frac(df, size = 1, replace = TRUE)
}
```

Now, make a tibble to keep track evertything
```{r}
boot_strap_df = 
  tibble(strap_number = 1:1000,
         strap_sample = rerun(1000, boot_sample(sim_df_nonconst)))
```

```{r}
boot_strap_df %>% 
  filter(strap_number %in% 1:2) %>% 
  mutate(strap_sample = map(strap_sample, ~arrange(.x, x))) %>% 
  pull(strap_sample)
```


```{r}
bootstrap_results = 
  boot_strap_df %>% 
  mutate(
    models = map(strap_sample, ~lm(y ~ x, data = .x) ),
    results = map(models, broom::tidy)) %>% 
  select(-strap_sample, -models) %>% 
  unnest(results) 

bootstrap_results %>% 
  ggplot(aes(x = estimate)) +
  geom_histogram() +
  facet_grid(~term, scales = "free")

lm(y~x, data = sim_df_nonconst) %>% 
  broom::tidy()


bootstrap_results %>% 
  group_by(term) %>% 
  summarise(
    se = sd(estimate)
  )
  
```

## Use `modelr`
```{r}
boot_straps = 
  sim_df_nonconst %>% 
  modelr::bootstrap(n = 1000) 

boot_straps$strap[[1]]
```

## airbnb data
```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  select(price, stars, boro, neighborhood, room_type)
```

```{r}
nyc_airbnb %>% 
  ggplot(aes(x = stars, y = price, color = room_type)) + 
  geom_point() 
```




bootstrap

```{r}
boot_result=
nyc_airbnb %>% 
  filter(boro == "Manhattan") %>% 
  modelr::bootstrap(n = 100, id="strap_number") %>% 
  mutate(
    models = map(strap, ~ lm(price ~ stars + room_type, data = .x)),
    results = map(models, broom::tidy)) %>% 
  select(results,strap_number) %>% 
  unnest(results)

boot_result %>% 
  filter(term == "stars") %>% 
  ggplot(aes(x = estimate)) + geom_density()
```


```{r}
library(patchwork)

ggp_star_est = 
boot_result %>% 
  filter(term == "stars") %>% 
  ggplot(aes(x = estimate)) + geom_density()

ggp_scatter =
nyc_airbnb %>% 
  filter(boro == "Manhattan") %>% 
  ggplot(aes(x = stars, y = price, color = room_type)) + 
  geom_point() 
  
ggp_star_est + ggp_scatter
  
```





